# Generated by Django 4.0.4 on 2022-05-23 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_code', models.CharField(max_length=500, verbose_name='Authorization Code sent from Paystack')),
                ('last_digits', models.CharField(max_length=10, verbose_name='Last four digits of the card.')),
                ('card_type', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('expiry_date', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('bank', models.CharField(choices=[('044', 'Access Bank'), ('063', 'Access Bank (Diamond)'), ('050', 'Ecobank Nigeria'), ('070', 'Fidelity Bank'), ('011', 'First Bank of Nigeria'), ('214', 'First City Momument Bank'), ('058', 'Guaranty Trust Bank'), ('50211', 'Kuda Bank'), ('076', 'Polaris Bank'), ('125', 'Rubies MFB'), ('221', 'Stanbic IBTC Bank'), ('068', 'Standard Chatered Bank'), ('232', 'Sterling Bank'), ('032', 'Union Bank of Nigeria'), ('033', 'United Bank for Africa'), ('215', 'Unity Bank'), ('035', 'Wema Bank'), ('057', 'Zenith Bank')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
