# Generated by Django 4.0.4 on 2022-05-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_bankdetails_authorization_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=500, verbose_name='Authorization Code sent from Paystack'),
        ),
    ]
