# Generated by Django 4.0.4 on 2022-05-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_bankdetails_authorization_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='authorization_code',
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=500, verbose_name='Recipient Code sent from Paystack'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Return account name from Paystack on account number verified'),
        ),
    ]
