# Generated by Django 4.0.4 on 2022-05-18 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('investment_type', models.CharField(choices=[('naira', 'Naira'), ('usd', 'USD')], default='naira', max_length=20)),
                ('ytd_returns', models.CharField(max_length=10)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('high', 'High Risk')], max_length=20)),
                ('description', models.TextField()),
                ('price_per_unit', models.IntegerField()),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_type', models.CharField(choices=[('regular', 'Regular'), ('halal', 'Halal'), ('emergency', 'Emergency')], default='regular', max_length=20)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserSavingsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.savings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
