# Generated by Django 4.0.4 on 2022-05-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavingsplan',
            name='balance',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savings',
            name='savings_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('emergency', 'Emergency')], default='regular', max_length=20),
        ),
    ]
