# Generated by Django 4.0.4 on 2022-05-21 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0002_usersavingsplan_balance_alter_savings_savings_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savings',
            old_name='amount',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='savings',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserSavingsPlan',
        ),
    ]
