# Generated by Django 4.0.4 on 2022-05-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_savings_amount_alter_savings_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='amount',
            field=models.IntegerField(verbose_name="Amount to be saved periodically (or the initial amount, if it's a manual option)."),
        ),
        migrations.AlterField(
            model_name='savings',
            name='balance',
            field=models.IntegerField(verbose_name='Current balance left in the savings plan.'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='frequency',
            field=models.CharField(choices=[('manual', 'Manual'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='manual', max_length=20),
        ),
    ]
