# Generated by Django 4.0.4 on 2022-05-23 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0002_alter_stash_account_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stash',
            name='account_details',
        ),
        migrations.DeleteModel(
            name='BankDetails',
        ),
    ]
