# Generated by Django 4.0.4 on 2022-05-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0003_remove_stash_account_details_delete_bankdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
