# Generated by Django 4.0.4 on 2022-05-20 10:25

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_phone_number_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bvn',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('select', 'Select'), ('male', 'Male'), ('female', 'Female')], default='select', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
