# Generated by Django 4.0.4 on 2022-05-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_next_of_kin_nextofkin_user_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='pin',
            field=models.IntegerField(default=1234),
        ),
        migrations.AlterField(
            model_name='security',
            name='two_fa',
            field=models.BooleanField(default=False, verbose_name='Two Factor Authentication'),
        ),
    ]
