# Generated by Django 4.0.4 on 2022-05-23 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stash', '0003_remove_stash_account_details_delete_bankdetails'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('transfer.plan', 'transfer.plan'), ('transfer.bank', 'transfer.bank'), ('topup', 'topup')], max_length=20)),
                ('reference', models.CharField(max_length=20, verbose_name='Reference from Paystack')),
                ('status', models.CharField(choices=[('failed', 'failed'), ('pending', 'pending'), ('processed', 'processed')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stash.stash')),
            ],
            options={
                'verbose_name_plural': 'stash transactions',
            },
        ),
        migrations.CreateModel(
            name='PlanTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal')], max_length=20)),
                ('reference', models.CharField(max_length=20, verbose_name='Reference from Paystack')),
                ('status', models.CharField(choices=[('failed', 'failed'), ('pending', 'pending'), ('processed', 'processed')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'plan transactions',
            },
        ),
    ]
