# Generated by Django 3.2.4 on 2021-06-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestmentplan',
            name='balance',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
